In [1]:
import numpy as np

In [2]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [7]:
array.min(), array.max(), min(array), max(array)

(np.int64(10), np.int64(500), np.int64(10), np.int64(500))

In [6]:
array.sum(), sum(array)

(np.int64(1338), np.int64(1338))

In [5]:
array.mean()

np.float64(111.5)

In [9]:
array.argmin(), array.argmax()

(np.int64(3), np.int64(2))

In [10]:
l = [23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30]
l.index(30)

5

In [11]:
array[array > 100]

array([500, 310, 101, 203])

In [12]:
array[-1]

np.int64(30)

In [13]:
array[-2:]

array([203,  30])

In [14]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [16]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [17]:
array[(array % 3 == 0) | (array < 40)]

array([23, 10, 30, 20, 30, 30])